backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Wpisy (Archiwum)"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string", default: "Michał Rukszan"}
      - {label: "Treść", name: "body", widget: "markdown"}