backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "database"
    label: "Baza Danych"
    files:
      - label: "Wszystkie Artykuły"
        name: "articles"
        file: "baza-artykulow.json"
        fields:
          - label: "Wpisy"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Tytuł", name: "title", widget: "string"}
              - {label: "Link (bez spacji, np. luty-2026)", name: "slug", widget: "string"}
              - {label: "Zajawka na kafelek", name: "excerpt", widget: "text"}
              - {label: "Data publikacji", name: "date", widget: "datetime"}
              - {label: "Autor", name: "author", widget: "string", default: "Michał Rukszan"}
              - {label: "Treść artykułu", name: "body", widget: "markdown"}
