backend:
  name: github
  repo: MRux123/mr-blog
  branch: main
  base_url: https://rukszan.com
  auth_endpoint: blog/admin/auth.php

media_folder: "images"
public_folder: "/blog/images"

collections:
  - name: "database"
    label: "Newsy (Culture)"
    files:
      - label: "Wszystkie Artykuły"
        name: "articles"
        file: "baza-artykulow.json"
        fields:
          - label: "Wpisy"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Tytuł", name: "title", widget: "string"}
              - {label: "Link (bez spacji, np. luty-2026)", name: "slug", widget: "string"}
              - {label: "Zajawka na kafelek", name: "excerpt", widget: "text"}
              - {label: "Data publikacji", name: "date", widget: "datetime"}
              - {label: "Autor", name: "author", widget: "string", default: "Michał Rukszan"}
              - {label: "Treść artykułu", name: "body", widget: "markdown"}
              - {label: "Zdjęcie na dole (opcjonalne)", name: "bottom_image", widget: "image", required: false}

  - name: "blog_database"
    label: "Blog Osobisty"
    files:
      - label: "Wpisy na Bloga"
        name: "blog_posts"
        file: "baza-blog.json"
        fields:
          - label: "Wpisy"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Tytuł", name: "title", widget: "string"}
              - {label: "Link (bez spacji, np. moj-pierwszy-wpis)", name: "slug", widget: "string"}
              - {label: "Zajawka na kafelek", name: "excerpt", widget: "text"}
              - {label: "Data publikacji", name: "date", widget: "datetime"}
              - {label: "Autor", name: "author", widget: "string", default: "Michał Rukszan"}
              - {label: "Treść wpisu", name: "body", widget: "markdown"}
              - {label: "Zdjęcie na dole (opcjonalne)", name: "bottom_image", widget: "image", required: false}

